"""Curated YouTube learning resources catalog for Technea.

Features 24 comprehensive learning paths across 5 domains.
Every learning path includes 5 curated courses with real YouTube videos
from top educators (freeCodeCamp, Programming with Mosh, Traversy Media, Bro Code,
CodeWithHarry, Tech With Tim, The Net Ninja, Fireship, CS50, MIT OpenCourseWare,
DeepLearning.AI, Andrew Ng, Google Developers, TensorFlow, HuggingFace),
plus multi-lesson playlists for the embedded Course Player.
"""

YOUTUBE_CATALOG = [
    # =========================================================================
    # PROGRAMMING DOMAIN (5 Paths)
    # =========================================================================
    {
        "skill": {
            "name": "Python",
            "category": "Programming",
            "description": "General-purpose language powering web services, automation, scientific computing, and AI.",
        },
        "learning_path": {
            "title": "Python Fundamentals",
            "category": "Programming",
            "level": "Beginner",
            "duration": "4 Weeks",
            "description": "Master core syntax, dynamic typing, algorithmic thinking, and modern development idioms in Python.",
        },
        "roadmap_steps": [
            {"step_number": 1, "title": "Variables, Primitive Types & Expressions", "description": "Understand numerical types, string manipulation, booleans, arithmetic and logical operators."},
            {"step_number": 2, "title": "Conditionals, Branching & Truthiness", "description": "Control execution flows using if, elif, and else statements, matching patterns and boolean truth values."},
            {"step_number": 3, "title": "Iteration, Loops & Comprehensions", "description": "Harness while and for loops, iterate with range/enumerate/zip, and craft concise list/dict comprehensions."},
            {"step_number": 4, "title": "Functions, Scoping & Closures", "description": "Write reusable functions, positional/keyword parameters, *args, **kwargs, return values, and closures."},
            {"step_number": 5, "title": "Data Structures & Collections", "description": "Deep dive into lists, tuples, sets, dictionaries, and memory behaviors of mutable vs immutable structures."},
            {"step_number": 6, "title": "Object-Oriented Programming Foundations", "description": "Define classes, objects, magic dunder methods, inheritance, composition, and encapsulation."},
            {"step_number": 7, "title": "Modules, Virtual Environments & Packaging", "description": "Organize multi-file projects, isolate dependencies with venv, install packages with pip, and manage pyproject.toml."},
        ],
        "courses": [
            {
                "title": "Python for Beginners - Full Course",
                "description": "Comprehensive introduction to coding, data extraction, and web services taught by Mike Dane.",
                "platform": "YouTube / freeCodeCamp",
                "instructor": "Mike Dane",
                "duration": "4h 26m",
                "youtube_video_id": "rfscVS0vtbw",
                "youtube_url": "https://www.youtube.com/watch?v=rfscVS0vtbw",
                "thumbnail_url": "https://img.youtube.com/vi/rfscVS0vtbw/hqdefault.jpg",
                "playlist_url": "https://www.youtube.com/playlist?list=PLWKjhJtqVAbkmRvnFmOd4KhDdlK1oIq23",
                "lesson_order": 1,
                "lessons": [
                    {"lesson_order": 1, "title": "Introduction, Setup & First Program", "description": "Installing Python, setting up VS Code, and writing your first print statement.", "youtube_video_id": "rfscVS0vtbw", "duration": "25 mins"},
                    {"lesson_order": 2, "title": "Variables, Strings & Working with Numbers", "description": "Understanding variables, string indexing, methods, and mathematical operations.", "youtube_video_id": "rfscVS0vtbw", "duration": "45 mins"},
                    {"lesson_order": 3, "title": "Conditionals, If Statements & Comparisons", "description": "Branching logic with if/elif/else statements and boolean logic.", "youtube_video_id": "rfscVS0vtbw", "duration": "35 mins"},
                    {"lesson_order": 4, "title": "Loops, Dictionaries & Functions", "description": "While loops, for loops, key-value mappings, and building reusable functions.", "youtube_video_id": "rfscVS0vtbw", "duration": "50 mins"},
                    {"lesson_order": 5, "title": "Classes, Objects & Building a Quiz", "description": "Introduction to object-oriented principles and building an interactive quiz project.", "youtube_video_id": "rfscVS0vtbw", "duration": "40 mins"},
                ],
            },
            {
                "title": "Python Tutorial for Beginners",
                "description": "Clean, highly practical introduction to Python fundamentals by Mosh Hamedani.",
                "platform": "YouTube / Programming with Mosh",
                "instructor": "Mosh Hamedani",
                "duration": "1h 05m",
                "youtube_video_id": "_uQrJ0TkZlc",
                "youtube_url": "https://www.youtube.com/watch?v=_uQrJ0TkZlc",
                "thumbnail_url": "https://img.youtube.com/vi/_uQrJ0TkZlc/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 2,
                "lessons": [
                    {"lesson_order": 1, "title": "Getting Started & Writing Clean Code", "description": "Setting up the Python interpreter and understanding script execution.", "youtube_video_id": "_uQrJ0TkZlc", "duration": "15 mins"},
                    {"lesson_order": 2, "title": "Variables & Type Conversions", "description": "Handling user inputs, string transformations, and numeric conversions.", "youtube_video_id": "_uQrJ0TkZlc", "duration": "18 mins"},
                    {"lesson_order": 3, "title": "Control Flow & Comparison Operators", "description": "Logical operators, conditional evaluation, and building a weight converter.", "youtube_video_id": "_uQrJ0TkZlc", "duration": "16 mins"},
                    {"lesson_order": 4, "title": "Lists, Tuples & Practical Collections", "description": "Manipulating list sequences, indexing, slicing, and tuple immutability.", "youtube_video_id": "_uQrJ0TkZlc", "duration": "16 mins"},
                ],
            },
            {
                "title": "CS50's Introduction to Programming with Python",
                "description": "Harvard's official collegiate introduction to computer science and programming in Python.",
                "platform": "YouTube / CS50",
                "instructor": "David J. Malan",
                "duration": "15h 56m",
                "youtube_video_id": "nLRL_NcnK-4",
                "youtube_url": "https://www.youtube.com/watch?v=nLRL_NcnK-4",
                "thumbnail_url": "https://img.youtube.com/vi/nLRL_NcnK-4/hqdefault.jpg",
                "playlist_url": "https://www.youtube.com/playlist?list=PLhQjrBD2T3817j24-GogXmWAmOlgL5CXO",
                "lesson_order": 3,
                "lessons": [
                    {"lesson_order": 1, "title": "Lecture 0: Functions & Variables", "description": "Syntax, print formatting, user inputs, function definitions, and variable scopes.", "youtube_video_id": "nLRL_NcnK-4", "duration": "1h 20m"},
                    {"lesson_order": 2, "title": "Lecture 1: Conditionals & Boolean Logic", "description": "Control flow, truth tables, match statements, and defensive programming.", "youtube_video_id": "nLRL_NcnK-4", "duration": "1h 10m"},
                    {"lesson_order": 3, "title": "Lecture 2: Loops & Iterations", "description": "While loops, for loops, list iteration, dictionary iteration, and recursion.", "youtube_video_id": "nLRL_NcnK-4", "duration": "1h 15m"},
                    {"lesson_order": 4, "title": "Lecture 3: Exceptions & Defensive Coding", "description": "Handling runtime errors with try/except/else/finally blocks.", "youtube_video_id": "nLRL_NcnK-4", "duration": "55 mins"},
                    {"lesson_order": 5, "title": "Lecture 4: Libraries & Modules", "description": "Using sys, random, requests, APIs, and building modular packages.", "youtube_video_id": "nLRL_NcnK-4", "duration": "1h 05m"},
                ],
            },
            {
                "title": "Python Full Course for Beginners",
                "description": "Comprehensive, fast-paced hands-on Python tutorial with 100+ concepts covered.",
                "platform": "YouTube / Bro Code",
                "instructor": "Bro Code",
                "duration": "12h 00m",
                "youtube_video_id": "XKHEz6rJS3t",
                "youtube_url": "https://www.youtube.com/watch?v=XKHEz6rJS3t",
                "thumbnail_url": "https://img.youtube.com/vi/XKHEz6rJS3t/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 4,
                "lessons": [
                    {"lesson_order": 1, "title": "Variables, Data Types & Math Functions", "description": "Core primitives, arithmetic shortcuts, and formatting string outputs.", "youtube_video_id": "XKHEz6rJS3t", "duration": "40 mins"},
                    {"lesson_order": 2, "title": "Lists, Sets, Tuples & Dictionaries", "description": "Complete breakdown of Python collections and common access patterns.", "youtube_video_id": "XKHEz6rJS3t", "duration": "55 mins"},
                    {"lesson_order": 3, "title": "Object-Oriented Programming & Inheritance", "description": "Class definitions, super() calls, abstract methods, and polymorphism.", "youtube_video_id": "XKHEz6rJS3t", "duration": "50 mins"},
                    {"lesson_order": 4, "title": "File Detection, Reading & Writing", "description": "Working with the OS module, file I/O operations, and context managers.", "youtube_video_id": "XKHEz6rJS3t", "duration": "35 mins"},
                ],
            },
            {
                "title": "Python Tutorial for Beginners - Full Course",
                "description": "Step-by-step introduction to Python programming by Tech With Tim.",
                "platform": "YouTube / Tech With Tim",
                "instructor": "Tim Ruscica",
                "duration": "2h 45m",
                "youtube_video_id": "mDKM-JtUhhc",
                "youtube_url": "https://www.youtube.com/watch?v=mDKM-JtUhhc",
                "thumbnail_url": "https://img.youtube.com/vi/mDKM-JtUhhc/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 5,
                "lessons": [
                    {"lesson_order": 1, "title": "Installation, Syntax & Basic Operations", "description": "Setting up the environment and learning foundational syntax rules.", "youtube_video_id": "mDKM-JtUhhc", "duration": "30 mins"},
                    {"lesson_order": 2, "title": "Compound Conditions & Looping Structures", "description": "Chaining boolean conditions, while loops, and for loop iterations.", "youtube_video_id": "mDKM-JtUhhc", "duration": "40 mins"},
                    {"lesson_order": 3, "title": "Functions & Scope Management", "description": "Parameters, default values, return values, and global vs local scopes.", "youtube_video_id": "mDKM-JtUhhc", "duration": "35 mins"},
                    {"lesson_order": 4, "title": "Object Oriented Programming in Python", "description": "Constructors, instance methods, class attributes, and clean OOP design.", "youtube_video_id": "mDKM-JtUhhc", "duration": "40 mins"},
                ],
            },
        ],
    },

    # =========================================================================
    # Java Programming (Java)
    # =========================================================================
    {
        "skill": {
            "name": "Java",
            "category": "Programming",
            "description": "Object-oriented, statically typed platform powering enterprise backends and Android applications.",
        },
        "learning_path": {
            "title": "Java Programming",
            "category": "Programming",
            "level": "Beginner to Intermediate",
            "duration": "6 Weeks",
            "description": "Develop strong object-oriented principles, understand the JVM ecosystem, and build scalable Java services.",
        },
        "roadmap_steps": [
            {"step_number": 1, "title": "JVM, JRE, JDK & Development Setup", "description": "Understand Java compilation bytecode lifecycle, classpaths, and IDE setup."},
            {"step_number": 2, "title": "Primitive Data Types & Control Structures", "description": "Work with numerical types, booleans, conditionals, loops, and switches."},
            {"step_number": 3, "title": "OOP: Classes, Encapsulation & Inheritance", "description": "Constructors, access modifiers, method overriding, and polymorphism."},
            {"step_number": 4, "title": "Interfaces, Abstract Classes & Records", "description": "Contract-driven programming, default methods, and immutable records."},
            {"step_number": 5, "title": "Java Collections Framework & Generics", "description": "List, Set, Map hierarchies, hashing algorithms, and type-safe generics."},
            {"step_number": 6, "title": "Exceptions & File I/O Streams", "description": "Checked vs unchecked exceptions, try-with-resources, and modern java.nio."},
            {"step_number": 7, "title": "Lambdas, Streams & Concurrency Basics", "description": "Functional interfaces, stream transformations, threads, and modern concurrency."},
        ],
        "courses": [
            {
                "title": "Java Tutorial for Beginners",
                "description": "In-depth enterprise Java programming course covering core syntax and OOP architecture.",
                "platform": "YouTube / freeCodeCamp",
                "instructor": "Nelson Djalo (Amigoscode)",
                "duration": "9h 30m",
                "youtube_video_id": "A74TOX803D0",
                "youtube_url": "https://www.youtube.com/watch?v=A74TOX803D0",
                "thumbnail_url": "https://img.youtube.com/vi/A74TOX803D0/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 1,
                "lessons": [
                    {"lesson_order": 1, "title": "Java Fundamentals & Setup", "description": "JDK installation, IntelliJ IDEA, and your first compiled Java class.", "youtube_video_id": "A74TOX803D0", "duration": "45 mins"},
                    {"lesson_order": 2, "title": "Primitive vs Reference Types", "description": "Memory allocation on Heap vs Stack, primitive wrappers, and Strings.", "youtube_video_id": "A74TOX803D0", "duration": "55 mins"},
                    {"lesson_order": 3, "title": "Control Flow & Decision Making", "description": "Branching, loops, break/continue statements, and logical evaluation.", "youtube_video_id": "A74TOX803D0", "duration": "40 mins"},
                    {"lesson_order": 4, "title": "Object-Oriented Programming in Java", "description": "Classes, constructors, getters/setters, encapsulation, and inheritance.", "youtube_video_id": "A74TOX803D0", "duration": "1h 10m"},
                ],
            },
            {
                "title": "Java Tutorial for Beginners",
                "description": "Clear and visual guide to core Java concepts by Mosh Hamedani.",
                "platform": "YouTube / Programming with Mosh",
                "instructor": "Mosh Hamedani",
                "duration": "2h 30m",
                "youtube_video_id": "eIrMbAQSU34",
                "youtube_url": "https://www.youtube.com/watch?v=eIrMbAQSU34",
                "thumbnail_url": "https://img.youtube.com/vi/eIrMbAQSU34/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 2,
                "lessons": [
                    {"lesson_order": 1, "title": "Setting Up & First Java Code", "description": "Anatomy of a Java program, main method, and compilation step.", "youtube_video_id": "eIrMbAQSU34", "duration": "30 mins"},
                    {"lesson_order": 2, "title": "Types, Arrays & Constants", "description": "Declaring variables, multi-dimensional arrays, and constant values.", "youtube_video_id": "eIrMbAQSU34", "duration": "35 mins"},
                    {"lesson_order": 3, "title": "Control Flow & Building a Mortgage Calculator", "description": "Applying conditional logic and arithmetic formulas to a real project.", "youtube_video_id": "eIrMbAQSU34", "duration": "45 mins"},
                ],
            },
            {
                "title": "Java Full Course",
                "description": "The ultimate zero-to-hero Java programming marathon covering syntax, OOP, and GUIs.",
                "platform": "YouTube / Bro Code",
                "instructor": "Bro Code",
                "duration": "12h 00m",
                "youtube_video_id": "Qgl81fPcLc8",
                "youtube_url": "https://www.youtube.com/watch?v=Qgl81fPcLc8",
                "thumbnail_url": "https://img.youtube.com/vi/Qgl81fPcLc8/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 3,
                "lessons": [
                    {"lesson_order": 1, "title": "Core Syntax, Operators & Math", "description": "Data types, console scanning with Scanner, and expressions.", "youtube_video_id": "Qgl81fPcLc8", "duration": "50 mins"},
                    {"lesson_order": 2, "title": "Arrays & ArrayLists in Java", "description": "Static arrays, dynamic ArrayLists, and iterating over collections.", "youtube_video_id": "Qgl81fPcLc8", "duration": "45 mins"},
                    {"lesson_order": 3, "title": "OOP: Polymorphism & Interfaces", "description": "Overriding methods, abstract contracts, and polymorphism in action.", "youtube_video_id": "Qgl81fPcLc8", "duration": "55 mins"},
                    {"lesson_order": 4, "title": "Exception Handling & File Writing", "description": "Catching exceptions cleanly and writing files with FileWriter.", "youtube_video_id": "Qgl81fPcLc8", "duration": "40 mins"},
                ],
            },
            {
                "title": "Java Tutorial for Beginners in Hindi",
                "description": "Comprehensive Hindi Java tutorial explaining every core concept with visual examples.",
                "platform": "YouTube / CodeWithHarry",
                "instructor": "CodeWithHarry",
                "duration": "2h 15m",
                "youtube_video_id": "ntLJmHOJ0ME",
                "youtube_url": "https://www.youtube.com/watch?v=ntLJmHOJ0ME",
                "thumbnail_url": "https://img.youtube.com/vi/ntLJmHOJ0ME/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 4,
                "lessons": [
                    {"lesson_order": 1, "title": "Java Architecture & Hello World", "description": "JDK, JRE, JVM explanation and compiling your first Java file.", "youtube_video_id": "ntLJmHOJ0ME", "duration": "30 mins"},
                    {"lesson_order": 2, "title": "Variables, Literals & Data Types", "description": "Primitive types, size in memory, and type casting rules.", "youtube_video_id": "ntLJmHOJ0ME", "duration": "35 mins"},
                    {"lesson_order": 3, "title": "Conditionals & Loops in Java", "description": "If-else statements, switch-case, while loops, and for-each loops.", "youtube_video_id": "ntLJmHOJ0ME", "duration": "40 mins"},
                ],
            },
            {
                "title": "Java Course 2024",
                "description": "Comprehensive architectural guide to Java enterprise development by Telusko.",
                "platform": "YouTube / Telusko",
                "instructor": "Navin Reddy",
                "duration": "12h 00m",
                "youtube_video_id": "BGTx91t8q50",
                "youtube_url": "https://www.youtube.com/watch?v=BGTx91t8q50",
                "thumbnail_url": "https://img.youtube.com/vi/BGTx91t8q50/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 5,
                "lessons": [
                    {"lesson_order": 1, "title": "Java Fundamentals & Memory Structure", "description": "JVM memory model, stack vs heap, and bytecode execution.", "youtube_video_id": "BGTx91t8q50", "duration": "1h 00m"},
                    {"lesson_order": 2, "title": "Object Oriented Design & Encapsulation", "description": "Building classes, data hiding, constructors, and method overloading.", "youtube_video_id": "BGTx91t8q50", "duration": "1h 10m"},
                    {"lesson_order": 3, "title": "Collections, Generics & Streams API", "description": "Modern Collections, ArrayList, HashMap, and Stream pipeline processing.", "youtube_video_id": "BGTx91t8q50", "duration": "1h 15m"},
                ],
            },
        ],
    },

    # =========================================================================
    # C++ Programming (C++)
    # =========================================================================
    {
        "skill": {
            "name": "C++",
            "category": "Programming",
            "description": "High-performance systems language with manual memory management and zero-cost abstractions.",
        },
        "learning_path": {
            "title": "C++ Programming",
            "category": "Programming",
            "level": "Intermediate",
            "duration": "6 Weeks",
            "description": "Understand pointers, references, memory layouts, RAII, and modern C++ standard library features.",
        },
        "roadmap_steps": [
            {"step_number": 1, "title": "Compilation Model, Headers & Preprocessor", "description": "Explore preprocessing directives, header guards, translation units, and linking."},
            {"step_number": 2, "title": "Pointers, References & Memory Management", "description": "Master raw pointers, address-of operator, dereferencing, and the stack vs heap."},
            {"step_number": 3, "title": "RAII & Smart Pointers (unique_ptr, shared_ptr)", "description": "Resource Acquisition Is Initialization pattern, eliminating manual deletes and leaks."},
            {"step_number": 4, "title": "OOP: Rule of 0/3/5 & Move Semantics", "description": "Constructors, destructors, copy/move constructors, copy/move assignment operators."},
            {"step_number": 5, "title": "Templates & Generic Programming", "description": "Function templates, class templates, template specialization, and type deduction."},
            {"step_number": 6, "title": "Standard Template Library (STL)", "description": "std::vector, std::map, iterators, algorithms, and lambda expressions."},
            {"step_number": 7, "title": "Modern C++ (C++17/20/23) Features", "description": "Concepts, ranges, structured bindings, std::optional, and constexpr evaluation."},
        ],
        "courses": [
            {
                "title": "C++ Full Course for Beginners",
                "description": "Complete beginner course by Caleb Curry exploring foundational C++ syntax and pointers.",
                "platform": "YouTube / freeCodeCamp",
                "instructor": "Caleb Curry",
                "duration": "4h 01m",
                "youtube_video_id": "vLnPwxZdW4Y",
                "youtube_url": "https://www.youtube.com/watch?v=vLnPwxZdW4Y",
                "thumbnail_url": "https://img.youtube.com/vi/vLnPwxZdW4Y/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 1,
                "lessons": [
                    {"lesson_order": 1, "title": "Introduction, Compilation & Basics", "description": "Compiling with g++, understanding main(), and basic console I/O.", "youtube_video_id": "vLnPwxZdW4Y", "duration": "40 mins"},
                    {"lesson_order": 2, "title": "Variables, Data Types & Operators", "description": "Integers, floating points, characters, and arithmetic operators.", "youtube_video_id": "vLnPwxZdW4Y", "duration": "45 mins"},
                    {"lesson_order": 3, "title": "Control Flow, Conditionals & Loops", "description": "If statements, switch statements, while and for loops.", "youtube_video_id": "vLnPwxZdW4Y", "duration": "40 mins"},
                    {"lesson_order": 4, "title": "Pointers & Memory Addresses", "description": "Understanding pointers, references, and pointer arithmetic.", "youtube_video_id": "vLnPwxZdW4Y", "duration": "55 mins"},
                ],
            },
            {
                "title": "C++ Full Course",
                "description": "Comprehensive hands-on C++ programming tutorial covering core concepts to OOP.",
                "platform": "YouTube / Bro Code",
                "instructor": "Bro Code",
                "duration": "6h 00m",
                "youtube_video_id": "-TkoO8Z07hI",
                "youtube_url": "https://www.youtube.com/watch?v=-TkoO8Z07hI",
                "thumbnail_url": "https://img.youtube.com/vi/-TkoO8Z07hI/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 2,
                "lessons": [
                    {"lesson_order": 1, "title": "C++ Basics & Arithmetic Operations", "description": "Setting up IDE, variables, const keyword, and math operations.", "youtube_video_id": "-TkoO8Z07hI", "duration": "45 mins"},
                    {"lesson_order": 2, "title": "Functions, Overloading & Scopes", "description": "Defining functions, function overloading, and variable scopes.", "youtube_video_id": "-TkoO8Z07hI", "duration": "45 mins"},
                    {"lesson_order": 3, "title": "Arrays, Vectors & Pass-by-Reference", "description": "Static arrays, dynamic vectors, and passing references into functions.", "youtube_video_id": "-TkoO8Z07hI", "duration": "50 mins"},
                    {"lesson_order": 4, "title": "Pointers, Dynamic Memory & OOP", "description": "new and delete operators, raw pointers, classes, and inheritance.", "youtube_video_id": "-TkoO8Z07hI", "duration": "1h 00m"},
                ],
            },
            {
                "title": "How C++ Works - C++ Series",
                "description": "Industry-standard series breaking down how C++ really works under the hood.",
                "platform": "YouTube / The Cherno",
                "instructor": "The Cherno",
                "duration": "15h 00m",
                "youtube_video_id": "18c3MTX0PK0",
                "youtube_url": "https://www.youtube.com/watch?v=18c3MTX0PK0",
                "thumbnail_url": "https://img.youtube.com/vi/18c3MTX0PK0/hqdefault.jpg",
                "playlist_url": "https://www.youtube.com/playlist?list=PLlrATfBNZ98dudnM48yfGUldqGD0S4G6b",
                "lesson_order": 3,
                "lessons": [
                    {"lesson_order": 1, "title": "How the C++ Compiler Works", "description": "Understanding preprocessing, tokenization, assembly, and object files.", "youtube_video_id": "18c3MTX0PK0", "duration": "30 mins"},
                    {"lesson_order": 2, "title": "How the C++ Linker Works", "description": "Symbol resolution, linking object files, and diagnosing unresolved externals.", "youtube_video_id": "18c3MTX0PK0", "duration": "30 mins"},
                    {"lesson_order": 3, "title": "Pointers & References in Depth", "description": "Direct memory addresses, dereferencing, and reference mechanics in assembly.", "youtube_video_id": "18c3MTX0PK0", "duration": "35 mins"},
                    {"lesson_order": 4, "title": "Virtual Functions & Interfaces", "description": "V-tables, dynamic dispatch, abstract classes, and performance impacts.", "youtube_video_id": "18c3MTX0PK0", "duration": "35 mins"},
                ],
            },
            {
                "title": "C++ Tutorial for Beginners",
                "description": "Fast-paced introduction to C++ syntax, formatting, and operations by Mosh Hamedani.",
                "platform": "YouTube / Programming with Mosh",
                "instructor": "Mosh Hamedani",
                "duration": "1h 00m",
                "youtube_video_id": "ZzaPdXTrSb8",
                "youtube_url": "https://www.youtube.com/watch?v=ZzaPdXTrSb8",
                "thumbnail_url": "https://img.youtube.com/vi/ZzaPdXTrSb8/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 4,
                "lessons": [
                    {"lesson_order": 1, "title": "Getting Started with C++", "description": "Writing your first program, compilation, and console output.", "youtube_video_id": "ZzaPdXTrSb8", "duration": "15 mins"},
                    {"lesson_order": 2, "title": "Variables, Constants & Data Types", "description": "Fundamental types, narrow casting, and constant expressions.", "youtube_video_id": "ZzaPdXTrSb8", "duration": "20 mins"},
                    {"lesson_order": 3, "title": "Expressions & Mathematical Operations", "description": "Order of operations, modulus, and formatting output streams.", "youtube_video_id": "ZzaPdXTrSb8", "duration": "25 mins"},
                ],
            },
            {
                "title": "C++ Complete Course",
                "description": "Comprehensive Hindi C++ guide from zero to advanced object-oriented programming.",
                "platform": "YouTube / CodeWithHarry",
                "instructor": "CodeWithHarry",
                "duration": "2h 20m",
                "youtube_video_id": "yGB9jhsEsr8",
                "youtube_url": "https://www.youtube.com/watch?v=yGB9jhsEsr8",
                "thumbnail_url": "https://img.youtube.com/vi/yGB9jhsEsr8/hqdefault.jpg",
                "playlist_url": None,
                "lesson_order": 5,
                "lessons": [
                    {"lesson_order": 1, "title": "Introduction to C++ & Basic Structure", "description": "Headers, main function, and the standard iostream namespace.", "youtube_video_id": "yGB9jhsEsr8", "duration": "30 mins"},
                    {"lesson_order": 2, "title": "Variables, Comments & Data Types", "description": "Local vs global variables, data types, and console input/output.", "youtube_video_id": "yGB9jhsEsr8", "duration": "35 mins"},
                    {"lesson_order": 3, "title": "Control Structures & Functions", "description": "If-else conditions, loops, and function prototyping.", "youtube_video_id": "yGB9jhsEsr8", "duration": "40 mins"},
                ],
            },
        ],
    },
]
