"""add skill_id to learning_paths and learning_path_id to courses

Revision ID: 7ad04231ef7d
Revises: ab700f45f569
Create Date: 2026-10-10 15:05:27.386171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad04231ef7d'
down_revision: Union[str, None] = 'ab700f45f569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('learning_path_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_courses_learning_path_id'), 'courses', ['learning_path_id'], unique=False)
    op.create_foreign_key('fk_courses_learning_path_id_learning_paths', 'courses', 'learning_paths', ['learning_path_id'], ['id'], ondelete='SET NULL')
    op.add_column('learning_paths', sa.Column('skill_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_learning_paths_skill_id'), 'learning_paths', ['skill_id'], unique=False)
    op.create_foreign_key('fk_learning_paths_skill_id_skills', 'learning_paths', 'skills', ['skill_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_learning_paths_skill_id_skills', 'learning_paths', type_='foreignkey')
    op.drop_index(op.f('ix_learning_paths_skill_id'), table_name='learning_paths')
    op.drop_column('learning_paths', 'skill_id')
    op.drop_constraint('fk_courses_learning_path_id_learning_paths', 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_learning_path_id'), table_name='courses')
    op.drop_column('courses', 'learning_path_id')
    # ### end Alembic commands ###

