"""add_youtube_and_lessons_to_courses

Revision ID: e1381a82450e
Revises: 7ad04231ef7d
Create Date: 2026-10-10 16:30:11.423250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1381a82450e'
down_revision: Union[str, None] = '7ad04231ef7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=100), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('lesson_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.add_column('courses', sa.Column('youtube_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('youtube_video_id', sa.String(length=100), nullable=True))
    op.add_column('courses', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('playlist_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('lesson_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'lesson_order')
    op.drop_column('courses', 'playlist_url')
    op.drop_column('courses', 'thumbnail_url')
    op.drop_column('courses', 'youtube_video_id')
    op.drop_column('courses', 'youtube_url')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
